# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Internal Test Track on Google Play"
  lane :beta_internal do
    ENV["ENVFILE"] = ".env.beta"
    ENV["OTTODIY_APP_KEYSTORE_FILE"] = ENV["OTTODIY_BETA_APP_KEYSTORE_FILE"]
    gradle(task: "clean bundleBetaRelease")

    upload_to_play_store(
      package_name: 'com.ottodiy.beta',
      track: 'internal'
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    ENV["ENVFILE"] = ".env.production"
    gradle(task: "clean bundleProductionRelease")
    upload_to_play_store(
      package_name: 'com.ottodiy',
      track: 'internal'
    )
  end
end
